[package]
name = "ec"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]

[cairo]
enable-gas = false

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git" }
cairo_execute = "2.9.2"

[dev-dependencies]
cairo_test = "2.9.2"